# Generated by Django 3.2.16 on 2023-11-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='payment_Terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_terms'),
        ),
    ]
