# Generated by Django 3.2.16 on 2023-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_companies_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='end',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
