# Generated by Django 3.2.16 on 2023-11-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_companies_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='end',
            new_name='payTerm_enddate',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='start_date',
            new_name='payTerm_startdate',
        ),
    ]
