# Generated by Django 4.2.3 on 2023-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20231110_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
