# Generated by Django 3.2.16 on 2023-11-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20231110_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/staff')),
                ('status', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, default='staff', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='sales_vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.IntegerField(null=True)),
                ('sup_inv_no', models.CharField(max_length=255, null=True)),
                ('sup_inv_date', models.DateField(blank=True, null=True)),
                ('vouch_date', models.DateField(blank=True, null=True)),
                ('party_accname', models.CharField(max_length=255, null=True)),
                ('sales_ledger', models.CharField(max_length=255, null=True)),
                ('receipt_doc_no', models.CharField(max_length=255, null=True)),
                ('dispatched_through', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('carriername_agent', models.CharField(max_length=255, null=True)),
                ('bill_of_lading', models.CharField(max_length=255, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('motor_vehicle_no', models.CharField(max_length=255, null=True)),
                ('supplier', models.CharField(max_length=255, null=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('gst_treatment', models.CharField(max_length=255, null=True)),
                ('gst_number', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='sale_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('per', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('sales_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_vouchers')),
            ],
        ),
        migrations.AddField(
            model_name='receipt_note_no',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_vouchers'),
        ),
    ]
