# Generated by Django 3.2.16 on 2023-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20231122_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
