# Generated by Django 4.2.3 on 2023-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_companies_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='company_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
