# Generated by Django 4.2.3 on 2023-11-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_stock_itemcreation_per_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sale_voucher',
        ),
    ]
