# Generated by Django 4.2.3 on 2023-11-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_sales_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales_voucher',
        ),
    ]
