# Generated by Django 4.2.3 on 2023-11-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delete_sales_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.IntegerField(null=True)),
                ('sup_inv_no', models.CharField(max_length=255, null=True)),
                ('sup_inv_date', models.DateField(blank=True, null=True)),
                ('vouch_date', models.DateField(blank=True, null=True)),
                ('party_accname', models.CharField(max_length=255, null=True)),
                ('purchase_ledger', models.CharField(max_length=255, null=True)),
                ('receipt_doc_no', models.CharField(max_length=255, null=True)),
                ('dispatched_through', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('carriername_agent', models.CharField(max_length=255, null=True)),
                ('bill_of_lading', models.CharField(max_length=255, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('motor_vehicle_no', models.CharField(max_length=255, null=True)),
                ('supplier', models.CharField(max_length=255, null=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('gst_treatment', models.CharField(max_length=255, null=True)),
                ('gst_number', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
    ]
