# Generated by Django 3.2.16 on 2023-10-19 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20231017_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='contra_voucher',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AlterField(
            model_name='contra_particulars',
            name='contra_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.contra_voucher'),
        ),
    ]
