# Generated by Django 4.2.3 on 2023-11-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_sales_vouchers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales_vouchers',
        ),
    ]
