# Generated by Django 4.2.3 on 2023-11-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
