# Generated by Django 4.2.3 on 2023-11-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_sales_vouchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('per', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('sales_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_vouchers')),
            ],
        ),
    ]
