# Generated by Django 4.2.3 on 2023-11-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_sale_particulars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='receipt_note_no',
        ),
    ]
