# Generated by Django 4.2.3 on 2023-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_receipt_note_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='position',
            field=models.CharField(blank=True, default='staff', max_length=100, null=True),
        ),
    ]
