# Generated by Django 4.2.3 on 2023-11-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_logins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logins',
        ),
    ]
