# Generated by Django 4.2.3 on 2023-11-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_logins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('reg_user', models.CharField(max_length=70)),
            ],
        ),
    ]
