# Generated by Django 4.2.3 on 2023-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_companies_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='position',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, default='staff', max_length=100, null=True),
        ),
    ]
