# Generated by Django 4.2.3 on 2023-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_logins'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms_number', models.IntegerField(blank=True, null=True)),
                ('payment_terms_value', models.CharField(blank=True, max_length=100, null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
