# Generated by Django 4.2.3 on 2023-11-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_payment_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_terms',
        ),
    ]
