# Generated by Django 4.2.3 on 2023-11-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_distributor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
