# Generated by Django 4.2.3 on 2023-11-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_companies_distributors_companies_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='Distributors',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
