# Generated by Django 4.2.3 on 2023-11-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='Distributors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.distributor'),
        ),
    ]
