# Generated by Django 4.2.3 on 2023-11-08 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_companies_distributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='payTerm_enddate',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='payTerm_startdate',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
            preserve_default=False,
        ),
    ]
