# Generated by Django 4.2.3 on 2023-11-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_companies_payterm_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
